// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadAcconts():Promise<Array<main.Account>>;

export function SaveAccount(arg1:main.Account):Promise<void>;
