// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAcconts() {
  return window['go']['main']['Accountlogic']['LoadAcconts']();
}

export function SaveAccount(arg1) {
  return window['go']['main']['Accountlogic']['SaveAccount'](arg1);
}
