// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAccounts() {
  return window['go']['main']['AccountLogic']['LoadAccounts']();
}

export function SaveAccount(arg1) {
  return window['go']['main']['AccountLogic']['SaveAccount'](arg1);
}
